# Generated by Django 3.1.7 on 2021-06-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configureDataBase', '0002_auto_20210528_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedulecontroler',
            name='affectedServie',
            field=models.CharField(default=1, max_length=255, verbose_name='影响业务'),
            preserve_default=False,
        ),
    ]
