# Generated by Django 3.1.7 on 2021-06-09 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configureDataBase', '0005_auto_20210609_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='progressNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageDetail', models.TextField()),
                ('messageDate', models.DateTimeField()),
                ('messageAuthor', models.CharField(max_length=255)),
                ('userScheduleControlerNote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configureDataBase.userschedulecontroler')),
            ],
        ),
    ]
